version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./laravel:/var/www:z
      - ./nginx/conf.d:/etc/nginx/conf.d:z
      - ./logs:/var/log/nginx:z
    env_file:
      - .env
    ports:
      - "$PROJECT_PORT:80"
    tty:  true
    
    restart: unless-stopped
    depends_on:
      - cryptopro
    container_name: $NGINX_NAME

  cryptopro:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TEST_CA: $TEST_CA
    tty:  true
    env_file:
      - .env
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./laravel:/var/www
    container_name: $CPRO_NAME

  # composer:
  #   image: composer:2.0.8
  #   volumes:
  #     - ./laravel:/var/www/
  #   working_dir: /var/www/
  #   command: composer install
  #   depends_on:
  #     - lar8cpro
